name: Example Action

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      deployments: write
      contents: read
    steps:
      - uses: qoomon/actions--revoke-environment-deployment@main


  build-with-environment:
    runs-on: ubuntu-latest
    environment: test
    permissions:
      actions: read
      deployments: write
      contents: read
    steps:
      - uses: qoomon/actions--revoke-environment-deployment@main
